//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>IChannelInfoDao</c> is the DAO interface for <see cref="CMS.Domain.ChannelInfo"/>.</summary>
    public partial interface IChannelInfoDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

        /// <summary>Returns the Sort id of objects.</summary>
        int GetOrderID(long channelID);

		/// <summary>Finds a <see cref="ChannelInfo"/> instance by the primary key value.</summary>
		ChannelInfo Find(Int64 iD);

		/// <summary>Finds all ChannelInfo instances.</summary>
		IList<ChannelInfo> FindAll();
		
		/// <summary>Finds all ChannelInfo instances without Lob columns loaded.</summary>
		IList<ChannelInfo> QuickFindAll();
		
		/// <summary>Finds ChannelInfo instances by ParentChannelID value.</summary>
		IList<ChannelInfo> FindByParentChannelID(Int64? parentChannelID);
		
		/// <summary>Finds ChannelInfo instances by Name value.</summary>
		IList<ChannelInfo> FindByName(String name);
		
		/// <summary>Finds ChannelInfo instances by EnName value.</summary>
		IList<ChannelInfo> FindByEnName(String enName);
		
		/// <summary>Finds ChannelInfo instances by Type value.</summary>
		IList<ChannelInfo> FindByType(Int32 type);
		
		/// <summary>Finds ChannelInfo instances by Sort value.</summary>
		IList<ChannelInfo> FindBySort(Int32 sort);
		
		/// <summary>Finds ChannelInfo instances by ChannelUrlPart value.</summary>
		IList<ChannelInfo> FindByChannelUrlPart(String channelUrlPart);
		
		/// <summary>Finds ChannelInfo instances by Keyword value.</summary>
		IList<ChannelInfo> FindByKeyword(String keyword);
		
		/// <summary>Finds ChannelInfo instances by Description value.</summary>
		IList<ChannelInfo> FindByDescription(String description);
		
		/// <summary>Finds ChannelInfo instances by TemplateID value.</summary>
		IList<ChannelInfo> FindByTemplateID(Int64 templateID);
		
		/// <summary>Finds ChannelInfo instances by ListTemplateID value.</summary>
		IList<ChannelInfo> FindByListTemplateID(Int64? listTemplateID);
		
		/// <summary>Finds ChannelInfo instances by PagerID value.</summary>
		IList<ChannelInfo> FindByPagerID(Int32? pagerID);
		
		/// <summary>Finds ChannelInfo instances by ContentTemplateID value.</summary>
		IList<ChannelInfo> FindByContentTemplateID(Int64? contentTemplateID);
		
		/// <summary>Finds ChannelInfo instances by CreateTime value.</summary>
		IList<ChannelInfo> FindByCreateTime(DateTime createTime);
		
		/// <summary>Finds ChannelInfo instances by CreateUserID value.</summary>
		IList<ChannelInfo> FindByCreateUserID(Int64 createUserID);
		
		/// <summary>Finds ChannelInfo instances by ModifyTime value.</summary>
		IList<ChannelInfo> FindByModifyTime(DateTime modifyTime);
		
		/// <summary>Finds ChannelInfo instances by ModifyUserID value.</summary>
		IList<ChannelInfo> FindByModifyUserID(Int64 modifyUserID);
		
		/// <summary>Finds ChannelInfo instances by Status value.</summary>
		IList<ChannelInfo> FindByStatus(Int32 status);
		
		/// <summary>Inserts a new ChannelInfo instance into underlying database table.</summary>
		void Insert(ChannelInfo obj);
		
		/// <summary>Update the underlying database record of a ChannelInfo instance.</summary>
		void Update(ChannelInfo obj);
		
		/// <summary>Delete the underlying database record of a ChannelInfo instance.</summary>
		void Delete(ChannelInfo obj);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.ParentChannelID"/>.</summary>
		int DeleteByParentChannelID(Int64? parentChannelID);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.Name"/>.</summary>
		int DeleteByName(String name);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.EnName"/>.</summary>
		int DeleteByEnName(String enName);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.Type"/>.</summary>
		int DeleteByType(Int32 type);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.Sort"/>.</summary>
		int DeleteBySort(Int32 sort);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.ChannelUrlPart"/>.</summary>
		int DeleteByChannelUrlPart(String channelUrlPart);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.Keyword"/>.</summary>
		int DeleteByKeyword(String keyword);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.Description"/>.</summary>
		int DeleteByDescription(String description);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.TemplateID"/>.</summary>
		int DeleteByTemplateID(Int64 templateID);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.ListTemplateID"/>.</summary>
		int DeleteByListTemplateID(Int64? listTemplateID);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.PagerID"/>.</summary>
		int DeleteByPagerID(Int32? pagerID);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.ContentTemplateID"/>.</summary>
		int DeleteByContentTemplateID(Int64? contentTemplateID);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime createTime);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.CreateUserID"/>.</summary>
		int DeleteByCreateUserID(Int64 createUserID);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.ModifyTime"/>.</summary>
		int DeleteByModifyTime(DateTime modifyTime);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.ModifyUserID"/>.</summary>
		int DeleteByModifyUserID(Int64 modifyUserID);
		
        /// <summary>Deletes <see cref="ChannelInfo"/> instances by <see cref="ChannelInfo.Status"/>.</summary>
		int DeleteByStatus(Int32 status);
		
		/// <summary>Reload the underlying database record of a ChannelInfo instance.</summary>
		void Reload(ChannelInfo obj);
		
	}

}
