//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>IChannelPrivilegeDao</c> is the DAO interface for <see cref="CMS.Domain.ChannelPrivilege"/>.</summary>
    public partial interface IChannelPrivilegeDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="ChannelPrivilege"/> instance by the primary key value.</summary>
		ChannelPrivilege Find(Int32 iD);

		/// <summary>Finds all ChannelPrivilege instances.</summary>
		IList<ChannelPrivilege> FindAll();
		
		/// <summary>Finds all ChannelPrivilege instances without Lob columns loaded.</summary>
		IList<ChannelPrivilege> QuickFindAll();
		
		/// <summary>Finds ChannelPrivilege instances by RoleID value.</summary>
		IList<ChannelPrivilege> FindByRoleID(Int64 roleID);
		
		/// <summary>Finds ChannelPrivilege instances by ChannelID value.</summary>
		IList<ChannelPrivilege> FindByChannelID(Int64 channelID);
		
		/// <summary>Finds ChannelPrivilege instances by IsBrowse value.</summary>
		IList<ChannelPrivilege> FindByIsBrowse(Boolean isBrowse);
		
		/// <summary>Finds ChannelPrivilege instances by AddAuth value.</summary>
		IList<ChannelPrivilege> FindByAddAuth(Boolean addAuth);
		
		/// <summary>Finds ChannelPrivilege instances by EditAuth value.</summary>
		IList<ChannelPrivilege> FindByEditAuth(Boolean editAuth);
		
		/// <summary>Finds ChannelPrivilege instances by DelAuth value.</summary>
		IList<ChannelPrivilege> FindByDelAuth(Boolean delAuth);
		
		/// <summary>Finds ChannelPrivilege instances by AuditingAuth value.</summary>
		IList<ChannelPrivilege> FindByAuditingAuth(Boolean auditingAuth);
		
		/// <summary>Finds ChannelPrivilege instances by CreateTime value.</summary>
		IList<ChannelPrivilege> FindByCreateTime(DateTime createTime);
		
		/// <summary>Finds ChannelPrivilege instances by CreateUserID value.</summary>
		IList<ChannelPrivilege> FindByCreateUserID(Int64 createUserID);
		
		/// <summary>Inserts a new ChannelPrivilege instance into underlying database table.</summary>
		void Insert(ChannelPrivilege obj);
		
		/// <summary>Update the underlying database record of a ChannelPrivilege instance.</summary>
		void Update(ChannelPrivilege obj);
		
		/// <summary>Delete the underlying database record of a ChannelPrivilege instance.</summary>
		void Delete(ChannelPrivilege obj);
		
        /// <summary>Deletes <see cref="ChannelPrivilege"/> instances by <see cref="ChannelPrivilege.RoleID"/>.</summary>
		int DeleteByRoleID(Int64 roleID);
		
        /// <summary>Deletes <see cref="ChannelPrivilege"/> instances by <see cref="ChannelPrivilege.ChannelID"/>.</summary>
		int DeleteByChannelID(Int64 channelID);
		
        /// <summary>Deletes <see cref="ChannelPrivilege"/> instances by <see cref="ChannelPrivilege.IsBrowse"/>.</summary>
		int DeleteByIsBrowse(Boolean isBrowse);
		
        /// <summary>Deletes <see cref="ChannelPrivilege"/> instances by <see cref="ChannelPrivilege.AddAuth"/>.</summary>
		int DeleteByAddAuth(Boolean addAuth);
		
        /// <summary>Deletes <see cref="ChannelPrivilege"/> instances by <see cref="ChannelPrivilege.EditAuth"/>.</summary>
		int DeleteByEditAuth(Boolean editAuth);
		
        /// <summary>Deletes <see cref="ChannelPrivilege"/> instances by <see cref="ChannelPrivilege.DelAuth"/>.</summary>
		int DeleteByDelAuth(Boolean delAuth);
		
        /// <summary>Deletes <see cref="ChannelPrivilege"/> instances by <see cref="ChannelPrivilege.AuditingAuth"/>.</summary>
		int DeleteByAuditingAuth(Boolean auditingAuth);
		
        /// <summary>Deletes <see cref="ChannelPrivilege"/> instances by <see cref="ChannelPrivilege.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime createTime);
		
        /// <summary>Deletes <see cref="ChannelPrivilege"/> instances by <see cref="ChannelPrivilege.CreateUserID"/>.</summary>
		int DeleteByCreateUserID(Int64 createUserID);
		
		/// <summary>Reload the underlying database record of a ChannelPrivilege instance.</summary>
		void Reload(ChannelPrivilege obj);
		
	}

}
