//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;
using System.Collections;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>IFeedBackDao</c> is the DAO interface for <see cref="CMS.Domain.FeedBack"/>.</summary>
    public partial interface IFeedBackDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="FeedBack"/> instance by the primary key value.</summary>
		FeedBack Find(Int64 iD);

		/// <summary>Finds all FeedBack instances.</summary>
		IList<FeedBack> FindAll();
		
		/// <summary>Finds all FeedBack instances without Lob columns loaded.</summary>
		IList<FeedBack> QuickFindAll();
		
		/// <summary>Finds FeedBack instances by Titile value.</summary>
		IList<FeedBack> FindByTitile(String titile);
		
		/// <summary>Finds FeedBack instances by Message value.</summary>
		IList<FeedBack> FindByMessage(String message);
		
		/// <summary>Finds FeedBack instances by UserName value.</summary>
		IList<FeedBack> FindByUserName(String userName);
		
		/// <summary>Finds FeedBack instances by Email value.</summary>
		IList<FeedBack> FindByEmail(String email);
		
		/// <summary>Finds FeedBack instances by Gender value.</summary>
		IList<FeedBack> FindByGender(String gender);
		
		/// <summary>Finds FeedBack instances by IP value.</summary>
		IList<FeedBack> FindByIP(String iP);
		
		/// <summary>Finds FeedBack instances by CreateTime value.</summary>
		IList<FeedBack> FindByCreateTime(DateTime createTime);
		
		/// <summary>Finds FeedBack instances by MessageType value.</summary>
        IList<FeedBack> FindByMessageType(Int32 messageType);
        IList<FeedBack> FindByMTStatus(Int32 messageType, Int32 status);
		
		/// <summary>Finds FeedBack instances by ReplyMessae value.</summary>
		IList<FeedBack> FindByReplyMessae(String replyMessae);
		
		/// <summary>Finds FeedBack instances by ReplyUserID value.</summary>
		IList<FeedBack> FindByReplyUserID(Int64 replyUserID);
		
		/// <summary>Finds FeedBack instances by ReplyTime value.</summary>
		IList<FeedBack> FindByReplyTime(DateTime replyTime);
		
		/// <summary>Finds FeedBack instances by Status value.</summary>
		IList<FeedBack> FindByStatus(Int32 status);
		
		/// <summary>Inserts a new FeedBack instance into underlying database table.</summary>
		void Insert(FeedBack obj);
		
		/// <summary>Update the underlying database record of a FeedBack instance.</summary>
		void Update(FeedBack obj);

        int UpdateStatus(Hashtable ht);

        void UpdateRemarksContent(FeedBack ht);
        int UpdateReplayContent(FeedBack obj);

		/// <summary>Delete the underlying database record of a FeedBack instance.</summary>
		int Delete(FeedBack obj);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.Titile"/>.</summary>
		int DeleteByTitile(String titile);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.Message"/>.</summary>
		int DeleteByMessage(String message);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.UserName"/>.</summary>
		int DeleteByUserName(String userName);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.Email"/>.</summary>
		int DeleteByEmail(String email);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.Gender"/>.</summary>
		int DeleteByGender(String gender);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.IP"/>.</summary>
		int DeleteByIP(String iP);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime createTime);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.MessageType"/>.</summary>
		int DeleteByMessageType(Int32 messageType);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.ReplyMessae"/>.</summary>
		int DeleteByReplyMessae(String replyMessae);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.ReplyUserID"/>.</summary>
		int DeleteByReplyUserID(Int64 replyUserID);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.ReplyTime"/>.</summary>
		int DeleteByReplyTime(DateTime replyTime);
		
        /// <summary>Deletes <see cref="FeedBack"/> instances by <see cref="FeedBack.Status"/>.</summary>
		int DeleteByStatus(Int32 status);
		
		/// <summary>Reload the underlying database record of a FeedBack instance.</summary>
		void Reload(FeedBack obj);
		
	}

}
