//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>IJobTypeDao</c> is the DAO interface for <see cref="CMS.Domain.JobType"/>.</summary>
    public partial interface IJobTypeDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="JobType"/> instance by the primary key value.</summary>
		JobType Find(Int64 iD);

		/// <summary>Finds all JobType instances.</summary>
		IList<JobType> FindAll();
		
		/// <summary>Finds all JobType instances without Lob columns loaded.</summary>
		IList<JobType> QuickFindAll();
		
		/// <summary>Finds JobType instances by Name value.</summary>
		IList<JobType> FindByName(String name);
		
		/// <summary>Finds JobType instances by Description value.</summary>
		IList<JobType> FindByDescription(String description);
		
		/// <summary>Inserts a new JobType instance into underlying database table.</summary>
        void Insert(JobType obj);
		
		/// <summary>Update the underlying database record of a JobType instance.</summary>
        int Update(JobType obj);
		
		/// <summary>Delete the underlying database record of a JobType instance.</summary>
		void Delete(JobType obj);
		
        /// <summary>Deletes <see cref="JobType"/> instances by <see cref="JobType.Name"/>.</summary>
		int DeleteByName(String name);
		
        /// <summary>Deletes <see cref="JobType"/> instances by <see cref="JobType.Description"/>.</summary>
		int DeleteByDescription(String description);
		
		/// <summary>Reload the underlying database record of a JobType instance.</summary>
		void Reload(JobType obj);
		
	}

}
