//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>INewsDocDao</c> is the DAO interface for <see cref="CMS.Domain.NewsDoc"/>.</summary>
    public partial interface INewsDocDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="NewsDoc"/> instance by the primary key value.</summary>
		NewsDoc Find(Int64 iD);

		/// <summary>Finds all NewsDoc instances.</summary>
		IList<NewsDoc> FindAll();
		
		/// <summary>Finds all NewsDoc instances without Lob columns loaded.</summary>
		IList<NewsDoc> QuickFindAll();
		
		/// <summary>Finds NewsDoc instances by ChannelID value.</summary>
		IList<NewsDoc> FindByChannelID(Int64 channelID);
		
		/// <summary>Finds NewsDoc instances by SpecialID value.</summary>
		IList<NewsDoc> FindBySpecialID(Int64? specialID);
		
		/// <summary>Finds NewsDoc instances by Title value.</summary>
		IList<NewsDoc> FindByTitle(String title);
		
		/// <summary>Finds NewsDoc instances by SubTitle value.</summary>
		IList<NewsDoc> FindBySubTitle(String subTitle);
		
		/// <summary>Finds NewsDoc instances by TitleColor value.</summary>
		IList<NewsDoc> FindByTitleColor(String titleColor);
		
		/// <summary>Finds NewsDoc instances by Author value.</summary>
		IList<NewsDoc> FindByAuthor(String author);
		
		/// <summary>Finds NewsDoc instances by PublicTime value.</summary>
		IList<NewsDoc> FindByPublicTime(DateTime publicTime);
		
		/// <summary>Finds NewsDoc instances by Content value.</summary>
		IList<NewsDoc> FindByContent(String content);
		
		/// <summary>Finds NewsDoc instances by Summary value.</summary>
		IList<NewsDoc> FindBySummary(String summary);
		
		/// <summary>Finds NewsDoc instances by IsTop value.</summary>
		IList<NewsDoc> FindByIsTop(Boolean isTop);
		
		/// <summary>Finds NewsDoc instances by IsRecommend value.</summary>
		IList<NewsDoc> FindByIsRecommend(Boolean isRecommend);
		
		/// <summary>Finds NewsDoc instances by IsBold value.</summary>
		IList<NewsDoc> FindByIsBold(Boolean isBold);
		
		/// <summary>Finds NewsDoc instances by Tags value.</summary>
		IList<NewsDoc> FindByTags(String tags);
		
		/// <summary>Finds NewsDoc instances by Linkurl value.</summary>
		IList<NewsDoc> FindByLinkurl(String linkurl);
		
		/// <summary>Finds NewsDoc instances by SmallImageUrl value.</summary>
		IList<NewsDoc> FindBySmallImageUrl(String smallImageUrl);
		
		/// <summary>Finds NewsDoc instances by Source value.</summary>
		IList<NewsDoc> FindBySource(String source);
		
		/// <summary>Finds NewsDoc instances by ClickCount value.</summary>
		IList<NewsDoc> FindByClickCount(Int32 clickCount);
		
		/// <summary>Finds NewsDoc instances by Status value.</summary>
		IList<NewsDoc> FindByStatus(Int32 status);
		
		/// <summary>Finds NewsDoc instances by CreateUserID value.</summary>
		IList<NewsDoc> FindByCreateUserID(Int64? createUserID);
		
		/// <summary>Finds NewsDoc instances by CreateUserIP value.</summary>
		IList<NewsDoc> FindByCreateUserIP(String createUserIP);
		
		/// <summary>Finds NewsDoc instances by CreateTime value.</summary>
		IList<NewsDoc> FindByCreateTime(DateTime? createTime);
		
		/// <summary>Finds NewsDoc instances by AuditUserID value.</summary>
		IList<NewsDoc> FindByAuditUserID(Int64? auditUserID);
		
		/// <summary>Finds NewsDoc instances by AuditTime value.</summary>
		IList<NewsDoc> FindByAuditTime(DateTime? auditTime);
		
		/// <summary>Finds NewsDoc instances by ModifyUserID value.</summary>
		IList<NewsDoc> FindByModifyUserID(Int64? modifyUserID);
		
		/// <summary>Finds NewsDoc instances by ModifyTime value.</summary>
		IList<NewsDoc> FindByModifyTime(DateTime? modifyTime);
		
		/// <summary>Finds NewsDoc instances by ModifyUserIP value.</summary>
		IList<NewsDoc> FindByModifyUserIP(String modifyUserIP);
		
		/// <summary>Finds NewsDoc instances by IsAuditing value.</summary>
		IList<NewsDoc> FindByIsAuditing(Int16 isAuditing);
		
		/// <summary>Finds NewsDoc instances by IsDelete value.</summary>
		IList<NewsDoc> FindByIsDelete(Int16 isDelete);
		
		/// <summary>Inserts a new NewsDoc instance into underlying database table.</summary>
		void Insert(NewsDoc obj);
		
		/// <summary>Update the underlying database record of a NewsDoc instance.</summary>
		void Update(NewsDoc obj);
		
		/// <summary>Delete the underlying database record of a NewsDoc instance.</summary>
		void Delete(NewsDoc obj);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.ChannelID"/>.</summary>
		int DeleteByChannelID(Int64 channelID);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.SpecialID"/>.</summary>
		int DeleteBySpecialID(Int64? specialID);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.Title"/>.</summary>
		int DeleteByTitle(String title);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.SubTitle"/>.</summary>
		int DeleteBySubTitle(String subTitle);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.TitleColor"/>.</summary>
		int DeleteByTitleColor(String titleColor);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.Author"/>.</summary>
		int DeleteByAuthor(String author);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.PublicTime"/>.</summary>
		int DeleteByPublicTime(DateTime publicTime);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.Content"/>.</summary>
		int DeleteByContent(String content);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.Summary"/>.</summary>
		int DeleteBySummary(String summary);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.IsTop"/>.</summary>
		int DeleteByIsTop(Boolean isTop);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.IsRecommend"/>.</summary>
		int DeleteByIsRecommend(Boolean isRecommend);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.IsBold"/>.</summary>
		int DeleteByIsBold(Boolean isBold);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.Tags"/>.</summary>
		int DeleteByTags(String tags);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.Linkurl"/>.</summary>
		int DeleteByLinkurl(String linkurl);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.SmallImageUrl"/>.</summary>
		int DeleteBySmallImageUrl(String smallImageUrl);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.Source"/>.</summary>
		int DeleteBySource(String source);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.ClickCount"/>.</summary>
		int DeleteByClickCount(Int32 clickCount);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.Status"/>.</summary>
		int DeleteByStatus(Int32 status);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.CreateUserID"/>.</summary>
		int DeleteByCreateUserID(Int64? createUserID);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.CreateUserIP"/>.</summary>
		int DeleteByCreateUserIP(String createUserIP);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime? createTime);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.AuditUserID"/>.</summary>
		int DeleteByAuditUserID(Int64? auditUserID);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.AuditTime"/>.</summary>
		int DeleteByAuditTime(DateTime? auditTime);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.ModifyUserID"/>.</summary>
		int DeleteByModifyUserID(Int64? modifyUserID);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.ModifyTime"/>.</summary>
		int DeleteByModifyTime(DateTime? modifyTime);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.ModifyUserIP"/>.</summary>
		int DeleteByModifyUserIP(String modifyUserIP);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.IsAuditing"/>.</summary>
		int DeleteByIsAuditing(Int16 isAuditing);
		
        /// <summary>Deletes <see cref="NewsDoc"/> instances by <see cref="NewsDoc.IsDelete"/>.</summary>
		int DeleteByIsDelete(Int16 isDelete);
		
		/// <summary>Reload the underlying database record of a NewsDoc instance.</summary>
		void Reload(NewsDoc obj);
		
	}

}
