//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>IPagerInfoDao</c> is the DAO interface for <see cref="CMS.Domain.PagerInfo"/>.</summary>
    public partial interface IPagerInfoDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="PagerInfo"/> instance by the primary key value.</summary>
		PagerInfo Find(Int32 pageID);

		/// <summary>Finds all PagerInfo instances.</summary>
		IList<PagerInfo> FindAll();
		
		/// <summary>Finds all PagerInfo instances without Lob columns loaded.</summary>
		IList<PagerInfo> QuickFindAll();
		
		/// <summary>Finds PagerInfo instances by DataType value.</summary>
		IList<PagerInfo> FindByDataType(Int32? dataType);
		
		/// <summary>Finds PagerInfo instances by Where value.</summary>
		IList<PagerInfo> FindByWhere(String where);
		
		/// <summary>Finds PagerInfo instances by OrderBy value.</summary>
		IList<PagerInfo> FindByOrderBy(String orderBy);
		
		/// <summary>Finds PagerInfo instances by PageSize value.</summary>
		IList<PagerInfo> FindByPageSize(Int32? pageSize);
		
		/// <summary>Finds PagerInfo instances by AddDate value.</summary>
		IList<PagerInfo> FindByAddDate(DateTime? addDate);
		
		/// <summary>Inserts a new PagerInfo instance into underlying database table.</summary>
		void Insert(PagerInfo obj);
		
		/// <summary>Update the underlying database record of a PagerInfo instance.</summary>
		void Update(PagerInfo obj);
		
		/// <summary>Delete the underlying database record of a PagerInfo instance.</summary>
		void Delete(PagerInfo obj);
		
        /// <summary>Deletes <see cref="PagerInfo"/> instances by <see cref="PagerInfo.DataType"/>.</summary>
		int DeleteByDataType(Int32? dataType);
		
        /// <summary>Deletes <see cref="PagerInfo"/> instances by <see cref="PagerInfo.Where"/>.</summary>
		int DeleteByWhere(String where);
		
        /// <summary>Deletes <see cref="PagerInfo"/> instances by <see cref="PagerInfo.OrderBy"/>.</summary>
		int DeleteByOrderBy(String orderBy);
		
        /// <summary>Deletes <see cref="PagerInfo"/> instances by <see cref="PagerInfo.PageSize"/>.</summary>
		int DeleteByPageSize(Int32? pageSize);
		
        /// <summary>Deletes <see cref="PagerInfo"/> instances by <see cref="PagerInfo.AddDate"/>.</summary>
		int DeleteByAddDate(DateTime? addDate);
		
		/// <summary>Reload the underlying database record of a PagerInfo instance.</summary>
		void Reload(PagerInfo obj);
		
	}

}
