//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>IRecommedInfoListDao</c> is the DAO interface for <see cref="CMS.Domain.RecommedInfoList"/>.</summary>
    public partial interface IRecommedInfoListDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="RecommedInfoList"/> instance by the primary key value.</summary>
		RecommedInfoList Find(Int64 iD);

		/// <summary>Finds all RecommedInfoList instances.</summary>
		IList<RecommedInfoList> FindAll();
		
		/// <summary>Finds all RecommedInfoList instances without Lob columns loaded.</summary>
		IList<RecommedInfoList> QuickFindAll();
		
		/// <summary>Finds RecommedInfoList instances by LocationID value.</summary>
		IList<RecommedInfoList> FindByLocationID(Int64? locationID);
		
		/// <summary>Finds RecommedInfoList instances by DocID value.</summary>
		IList<RecommedInfoList> FindByDocID(Int64? docID);
		
		/// <summary>Finds RecommedInfoList instances by Title value.</summary>
		IList<RecommedInfoList> FindByTitle(String title);
		
		/// <summary>Finds RecommedInfoList instances by SmallPicUrl value.</summary>
		IList<RecommedInfoList> FindBySmallPicUrl(String smallPicUrl);
		
		/// <summary>Finds RecommedInfoList instances by BigPicUrl value.</summary>
		IList<RecommedInfoList> FindByBigPicUrl(String bigPicUrl);
		
		/// <summary>Finds RecommedInfoList instances by Summary value.</summary>
		IList<RecommedInfoList> FindBySummary(String summary);
		
		/// <summary>Finds RecommedInfoList instances by LinkUrl value.</summary>
		IList<RecommedInfoList> FindByLinkUrl(String linkUrl);
		
		/// <summary>Finds RecommedInfoList instances by CreateUserID value.</summary>
		IList<RecommedInfoList> FindByCreateUserID(Int64? createUserID);
		
		/// <summary>Finds RecommedInfoList instances by CreateTime value.</summary>
		IList<RecommedInfoList> FindByCreateTime(DateTime? createTime);
		
		/// <summary>Finds RecommedInfoList instances by SortID value.</summary>
		IList<RecommedInfoList> FindBySortID(Int32 sortID);
		
		/// <summary>Finds RecommedInfoList instances by Status value.</summary>
		IList<RecommedInfoList> FindByStatus(Int32 status);
		
		/// <summary>Inserts a new RecommedInfoList instance into underlying database table.</summary>
		void Insert(RecommedInfoList obj);
		
		/// <summary>Update the underlying database record of a RecommedInfoList instance.</summary>
		void Update(RecommedInfoList obj);
		
		/// <summary>Delete the underlying database record of a RecommedInfoList instance.</summary>
		void Delete(RecommedInfoList obj);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.LocationID"/>.</summary>
		int DeleteByLocationID(Int64? locationID);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.DocID"/>.</summary>
		int DeleteByDocID(Int64? docID);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.Title"/>.</summary>
		int DeleteByTitle(String title);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.SmallPicUrl"/>.</summary>
		int DeleteBySmallPicUrl(String smallPicUrl);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.BigPicUrl"/>.</summary>
		int DeleteByBigPicUrl(String bigPicUrl);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.Summary"/>.</summary>
		int DeleteBySummary(String summary);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.LinkUrl"/>.</summary>
		int DeleteByLinkUrl(String linkUrl);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.CreateUserID"/>.</summary>
		int DeleteByCreateUserID(Int64? createUserID);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime? createTime);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.SortID"/>.</summary>
		int DeleteBySortID(Int32 sortID);
		
        /// <summary>Deletes <see cref="RecommedInfoList"/> instances by <see cref="RecommedInfoList.Status"/>.</summary>
		int DeleteByStatus(Int32 status);
		
		/// <summary>Reload the underlying database record of a RecommedInfoList instance.</summary>
		void Reload(RecommedInfoList obj);
		
	}

}
