//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>IRecommedPositionDao</c> is the DAO interface for <see cref="CMS.Domain.RecommedPosition"/>.</summary>
    public partial interface IRecommedPositionDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="RecommedPosition"/> instance by the primary key value.</summary>
		RecommedPosition Find(Int64 iD);

		/// <summary>Finds all RecommedPosition instances.</summary>
		IList<RecommedPosition> FindAll();
		
		/// <summary>Finds all RecommedPosition instances without Lob columns loaded.</summary>
		IList<RecommedPosition> QuickFindAll();
		
		/// <summary>Finds RecommedPosition instances by Name value.</summary>
		IList<RecommedPosition> FindByName(String name);
		
		/// <summary>Finds RecommedPosition instances by ChannelID value.</summary>
		IList<RecommedPosition> FindByChannelID(Int64 channelID);
		
		/// <summary>Finds RecommedPosition instances by LocationType value.</summary>
		IList<RecommedPosition> FindByLocationType(Int32 locationType);
		
		/// <summary>Finds RecommedPosition instances by Summary value.</summary>
		IList<RecommedPosition> FindBySummary(String summary);
		
		/// <summary>Finds RecommedPosition instances by CreateTime value.</summary>
		IList<RecommedPosition> FindByCreateTime(DateTime createTime);
		
		/// <summary>Inserts a new RecommedPosition instance into underlying database table.</summary>
		void Insert(RecommedPosition obj);
		
		/// <summary>Update the underlying database record of a RecommedPosition instance.</summary>
		void Update(RecommedPosition obj);
		
		/// <summary>Delete the underlying database record of a RecommedPosition instance.</summary>
		void Delete(RecommedPosition obj);
		
        /// <summary>Deletes <see cref="RecommedPosition"/> instances by <see cref="RecommedPosition.Name"/>.</summary>
		int DeleteByName(String name);
		
        /// <summary>Deletes <see cref="RecommedPosition"/> instances by <see cref="RecommedPosition.ChannelID"/>.</summary>
		int DeleteByChannelID(Int64 channelID);
		
        /// <summary>Deletes <see cref="RecommedPosition"/> instances by <see cref="RecommedPosition.LocationType"/>.</summary>
		int DeleteByLocationType(Int32 locationType);
		
        /// <summary>Deletes <see cref="RecommedPosition"/> instances by <see cref="RecommedPosition.Summary"/>.</summary>
		int DeleteBySummary(String summary);
		
        /// <summary>Deletes <see cref="RecommedPosition"/> instances by <see cref="RecommedPosition.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime createTime);
		
		/// <summary>Reload the underlying database record of a RecommedPosition instance.</summary>
		void Reload(RecommedPosition obj);
		
	}

}
