//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>IRolePrivilegeDao</c> is the DAO interface for <see cref="CMS.Domain.RolePrivilege"/>.</summary>
    public partial interface IRolePrivilegeDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="RolePrivilege"/> instance by the primary key value.</summary>
		RolePrivilege Find(Int64 iD);

		/// <summary>Finds all RolePrivilege instances.</summary>
		IList<RolePrivilege> FindAll();
		
		/// <summary>Finds all RolePrivilege instances without Lob columns loaded.</summary>
		IList<RolePrivilege> QuickFindAll();
		
		/// <summary>Finds RolePrivilege instances by RoleID value.</summary>
		IList<RolePrivilege> FindByRoleID(Int64 roleID);
		
		/// <summary>Finds RolePrivilege instances by ModuleID value.</summary>
		IList<RolePrivilege> FindByModuleID(Int64 moduleID);
		
		/// <summary>Finds RolePrivilege instances by CreateTime value.</summary>
		IList<RolePrivilege> FindByCreateTime(DateTime createTime);
		
		/// <summary>Finds RolePrivilege instances by CreateUserID value.</summary>
		IList<RolePrivilege> FindByCreateUserID(Int64 createUserID);
		
		/// <summary>Inserts a new RolePrivilege instance into underlying database table.</summary>
		void Insert(RolePrivilege obj);
		
		/// <summary>Update the underlying database record of a RolePrivilege instance.</summary>
		void Update(RolePrivilege obj);
		
		/// <summary>Delete the underlying database record of a RolePrivilege instance.</summary>
		void Delete(RolePrivilege obj);
		
        /// <summary>Deletes <see cref="RolePrivilege"/> instances by <see cref="RolePrivilege.RoleID"/>.</summary>
		int DeleteByRoleID(Int64 roleID);
		
        /// <summary>Deletes <see cref="RolePrivilege"/> instances by <see cref="RolePrivilege.ModuleID"/>.</summary>
		int DeleteByModuleID(Int64 moduleID);
		
        /// <summary>Deletes <see cref="RolePrivilege"/> instances by <see cref="RolePrivilege.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime createTime);
		
        /// <summary>Deletes <see cref="RolePrivilege"/> instances by <see cref="RolePrivilege.CreateUserID"/>.</summary>
		int DeleteByCreateUserID(Int64 createUserID);
		
		/// <summary>Reload the underlying database record of a RolePrivilege instance.</summary>
		void Reload(RolePrivilege obj);
		
	}

}
