//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>ISpecialChannelDao</c> is the DAO interface for <see cref="CMS.Domain.SpecialChannel"/>.</summary>
    public partial interface ISpecialChannelDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="SpecialChannel"/> instance by the primary key value.</summary>
		SpecialChannel Find(Int64 iD);

		/// <summary>Finds all SpecialChannel instances.</summary>
		IList<SpecialChannel> FindAll();
		
		/// <summary>Finds all SpecialChannel instances without Lob columns loaded.</summary>
		IList<SpecialChannel> QuickFindAll();
		
		/// <summary>Finds SpecialChannel instances by SpecialID value.</summary>
		IList<SpecialChannel> FindBySpecialID(Int64 specialID);
		
		/// <summary>Finds SpecialChannel instances by SubSpecialName value.</summary>
		IList<SpecialChannel> FindBySubSpecialName(String subSpecialName);
		
		/// <summary>Finds SpecialChannel instances by Url value.</summary>
		IList<SpecialChannel> FindByUrl(String url);
		
		/// <summary>Finds SpecialChannel instances by TemplateID value.</summary>
		IList<SpecialChannel> FindByTemplateID(Int64 templateID);
		
		/// <summary>Finds SpecialChannel instances by CreateUserID value.</summary>
		IList<SpecialChannel> FindByCreateUserID(Int64 createUserID);
		
		/// <summary>Finds SpecialChannel instances by CreateTiem value.</summary>
		IList<SpecialChannel> FindByCreateTiem(DateTime createTiem);
		
		/// <summary>Finds SpecialChannel instances by ModifyUserID value.</summary>
		IList<SpecialChannel> FindByModifyUserID(Int64 modifyUserID);
		
		/// <summary>Finds SpecialChannel instances by ModifyTime value.</summary>
		IList<SpecialChannel> FindByModifyTime(DateTime modifyTime);
		
		/// <summary>Inserts a new SpecialChannel instance into underlying database table.</summary>
		void Insert(SpecialChannel obj);
		
		/// <summary>Update the underlying database record of a SpecialChannel instance.</summary>
		void Update(SpecialChannel obj);
		
		/// <summary>Delete the underlying database record of a SpecialChannel instance.</summary>
		void Delete(SpecialChannel obj);
		
        /// <summary>Deletes <see cref="SpecialChannel"/> instances by <see cref="SpecialChannel.SpecialID"/>.</summary>
		int DeleteBySpecialID(Int64 specialID);
		
        /// <summary>Deletes <see cref="SpecialChannel"/> instances by <see cref="SpecialChannel.SubSpecialName"/>.</summary>
		int DeleteBySubSpecialName(String subSpecialName);
		
        /// <summary>Deletes <see cref="SpecialChannel"/> instances by <see cref="SpecialChannel.Url"/>.</summary>
		int DeleteByUrl(String url);
		
        /// <summary>Deletes <see cref="SpecialChannel"/> instances by <see cref="SpecialChannel.TemplateID"/>.</summary>
		int DeleteByTemplateID(Int64 templateID);
		
        /// <summary>Deletes <see cref="SpecialChannel"/> instances by <see cref="SpecialChannel.CreateUserID"/>.</summary>
		int DeleteByCreateUserID(Int64 createUserID);
		
        /// <summary>Deletes <see cref="SpecialChannel"/> instances by <see cref="SpecialChannel.CreateTiem"/>.</summary>
		int DeleteByCreateTiem(DateTime createTiem);
		
        /// <summary>Deletes <see cref="SpecialChannel"/> instances by <see cref="SpecialChannel.ModifyUserID"/>.</summary>
		int DeleteByModifyUserID(Int64 modifyUserID);
		
        /// <summary>Deletes <see cref="SpecialChannel"/> instances by <see cref="SpecialChannel.ModifyTime"/>.</summary>
		int DeleteByModifyTime(DateTime modifyTime);
		
		/// <summary>Reload the underlying database record of a SpecialChannel instance.</summary>
		void Reload(SpecialChannel obj);
		
	}

}
