//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>ITagDefineDao</c> is the DAO interface for <see cref="CMS.Domain.TagDefine"/>.</summary>
    public partial interface ITagDefineDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="TagDefine"/> instance by the primary key value.</summary>
		TagDefine Find(Int64 id);

		/// <summary>Finds all TagDefine instances.</summary>
		IList<TagDefine> FindAll();
		
		/// <summary>Finds all TagDefine instances without Lob columns loaded.</summary>
		IList<TagDefine> QuickFindAll();
		
		/// <summary>Finds TagDefine instances by TagName value.</summary>
		IList<TagDefine> FindByTagName(String tagName);
		
		/// <summary>Finds TagDefine instances by TagCode value.</summary>
		IList<TagDefine> FindByTagCode(String tagCode);
		
		/// <summary>Finds TagDefine instances by CreateTime value.</summary>
		IList<TagDefine> FindByCreateTime(DateTime createTime);
		
		/// <summary>Finds TagDefine instances by CreateUserID value.</summary>
		IList<TagDefine> FindByCreateUserID(Int64 createUserID);
		
		/// <summary>Finds TagDefine instances by ModifyTime value.</summary>
		IList<TagDefine> FindByModifyTime(DateTime modifyTime);
		
		/// <summary>Finds TagDefine instances by ModifyUserID value.</summary>
		IList<TagDefine> FindByModifyUserID(Int64 modifyUserID);
		
		/// <summary>Inserts a new TagDefine instance into underlying database table.</summary>
		void Insert(TagDefine obj);
		
		/// <summary>Update the underlying database record of a TagDefine instance.</summary>
		void Update(TagDefine obj);
		
		/// <summary>Delete the underlying database record of a TagDefine instance.</summary>
		void Delete(TagDefine obj);
		
        /// <summary>Deletes <see cref="TagDefine"/> instances by <see cref="TagDefine.TagName"/>.</summary>
		int DeleteByTagName(String tagName);
		
        /// <summary>Deletes <see cref="TagDefine"/> instances by <see cref="TagDefine.TagCode"/>.</summary>
		int DeleteByTagCode(String tagCode);
		
        /// <summary>Deletes <see cref="TagDefine"/> instances by <see cref="TagDefine.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime createTime);
		
        /// <summary>Deletes <see cref="TagDefine"/> instances by <see cref="TagDefine.CreateUserID"/>.</summary>
		int DeleteByCreateUserID(Int64 createUserID);
		
        /// <summary>Deletes <see cref="TagDefine"/> instances by <see cref="TagDefine.ModifyTime"/>.</summary>
		int DeleteByModifyTime(DateTime modifyTime);
		
        /// <summary>Deletes <see cref="TagDefine"/> instances by <see cref="TagDefine.ModifyUserID"/>.</summary>
		int DeleteByModifyUserID(Int64 modifyUserID);
		
		/// <summary>Reload the underlying database record of a TagDefine instance.</summary>
		void Reload(TagDefine obj);
		
	}

}
