//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>ITemplateDataUseInfoDao</c> is the DAO interface for <see cref="CMS.Domain.TemplateDataUseInfo"/>.</summary>
    public partial interface ITemplateDataUseInfoDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="TemplateDataUseInfo"/> instance by the primary key value.</summary>
		TemplateDataUseInfo Find(Int64 iD);

		/// <summary>Finds all TemplateDataUseInfo instances.</summary>
		IList<TemplateDataUseInfo> FindAll();
		
		/// <summary>Finds all TemplateDataUseInfo instances without Lob columns loaded.</summary>
		IList<TemplateDataUseInfo> QuickFindAll();
		
		/// <summary>Finds TemplateDataUseInfo instances by MainTemplateID value.</summary>
		IList<TemplateDataUseInfo> FindByMainTemplateID(Int64? mainTemplateID);
		
		/// <summary>Finds TemplateDataUseInfo instances by TemplateID value.</summary>
		IList<TemplateDataUseInfo> FindByTemplateID(Int64? templateID);
		
		/// <summary>Finds TemplateDataUseInfo instances by DataBlockID value.</summary>
		IList<TemplateDataUseInfo> FindByDataBlockID(Int64? dataBlockID);
		
		/// <summary>Inserts a new TemplateDataUseInfo instance into underlying database table.</summary>
		void Insert(TemplateDataUseInfo obj);
		
		/// <summary>Update the underlying database record of a TemplateDataUseInfo instance.</summary>
		void Update(TemplateDataUseInfo obj);
		
		/// <summary>Delete the underlying database record of a TemplateDataUseInfo instance.</summary>
		void Delete(TemplateDataUseInfo obj);
		
        /// <summary>Deletes <see cref="TemplateDataUseInfo"/> instances by <see cref="TemplateDataUseInfo.MainTemplateID"/>.</summary>
		int DeleteByMainTemplateID(Int64? mainTemplateID);
		
        /// <summary>Deletes <see cref="TemplateDataUseInfo"/> instances by <see cref="TemplateDataUseInfo.TemplateID"/>.</summary>
		int DeleteByTemplateID(Int64? templateID);
		
        /// <summary>Deletes <see cref="TemplateDataUseInfo"/> instances by <see cref="TemplateDataUseInfo.DataBlockID"/>.</summary>
		int DeleteByDataBlockID(Int64? dataBlockID);
		
		/// <summary>Reload the underlying database record of a TemplateDataUseInfo instance.</summary>
		void Reload(TemplateDataUseInfo obj);
		
	}

}
