//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>ITemplateBackupDao</c> is the DAO interface for <see cref="CMS.Domain.TemplateBackup"/>.</summary>
    public partial interface ITemplateBackupDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="TemplateBackup"/> instance by the primary key value.</summary>
		TemplateBackup Find(Int64 iD);

		/// <summary>Finds a <see cref="TemplateBackup"/> instance by the primary key value without Lob columns loaded.</summary>
		TemplateBackup QuickFind(Int64 iD);
		
		/// <summary>Finds all TemplateBackup instances.</summary>
		IList<TemplateBackup> FindAll();
		
		/// <summary>Finds all TemplateBackup instances without Lob columns loaded.</summary>
		IList<TemplateBackup> QuickFindAll();
		
		/// <summary>Finds TemplateBackup instances by TemplateID value.</summary>
		IList<TemplateBackup> FindByTemplateID(Int64 templateID);
		
		/// <summary>Finds TemplateBackup instances by TemplateID value without Lob columns loaded.</summary>
		IList<TemplateBackup> QuickFindByTemplateID(Int64 templateID);
		
		/// <summary>Finds TemplateBackup instances by CreateTime value.</summary>
		IList<TemplateBackup> FindByCreateTime(DateTime createTime);
		
		/// <summary>Finds TemplateBackup instances by CreateTime value without Lob columns loaded.</summary>
		IList<TemplateBackup> QuickFindByCreateTime(DateTime createTime);
		
		/// <summary>Inserts a new TemplateBackup instance into underlying database table.</summary>
		void Insert(TemplateBackup obj);
		
		/// <summary>Update the underlying database record of a TemplateBackup instance.</summary>
		void Update(TemplateBackup obj);
		
		/// <summary>Delete the underlying database record of a TemplateBackup instance.</summary>
		void Delete(TemplateBackup obj);
		
        /// <summary>Deletes <see cref="TemplateBackup"/> instances by <see cref="TemplateBackup.TemplateID"/>.</summary>
		int DeleteByTemplateID(Int64 templateID);
		
        /// <summary>Deletes <see cref="TemplateBackup"/> instances by <see cref="TemplateBackup.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime createTime);
		
		/// <summary>Reload the underlying database record of a TemplateBackup instance.</summary>
		void Reload(TemplateBackup obj);
		
	}

}
