//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.DaoIntf.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

using CMS.Domain;

namespace CMS.DataAccess.Interface {
	
    /// <summary><c>ITemplateInfoDao</c> is the DAO interface for <see cref="CMS.Domain.TemplateInfo"/>.</summary>
    public partial interface ITemplateInfoDao {        

		/// <summary>Returns the total count of objects.</summary>
		int GetCount();

		/// <summary>Finds a <see cref="TemplateInfo"/> instance by the primary key value.</summary>
		TemplateInfo Find(Int64 iD);

		/// <summary>Finds all TemplateInfo instances.</summary>
		IList<TemplateInfo> FindAll();
		
		/// <summary>Finds all TemplateInfo instances without Lob columns loaded.</summary>
		IList<TemplateInfo> QuickFindAll();
		
		/// <summary>Finds TemplateInfo instances by Name value.</summary>
		IList<TemplateInfo> FindByName(String name);
		
		/// <summary>Finds TemplateInfo instances by Type value.</summary>
		IList<TemplateInfo> FindByType(Int32? type);
		
		/// <summary>Finds TemplateInfo instances by TemplateCode value.</summary>
		IList<TemplateInfo> FindByTemplateCode(String templateCode);
		
		/// <summary>Finds TemplateInfo instances by CreateTime value.</summary>
		IList<TemplateInfo> FindByCreateTime(DateTime? createTime);
		
		/// <summary>Finds TemplateInfo instances by CreateUserID value.</summary>
		IList<TemplateInfo> FindByCreateUserID(Int64? createUserID);
		
		/// <summary>Finds TemplateInfo instances by ModifyTime value.</summary>
		IList<TemplateInfo> FindByModifyTime(DateTime? modifyTime);
		
		/// <summary>Finds TemplateInfo instances by ModifyUserID value.</summary>
		IList<TemplateInfo> FindByModifyUserID(Int64? modifyUserID);
		
		/// <summary>Finds TemplateInfo instances by Status value.</summary>
		IList<TemplateInfo> FindByStatus(Int32? status);
		
		/// <summary>Inserts a new TemplateInfo instance into underlying database table.</summary>
		void Insert(TemplateInfo obj);
		
		/// <summary>Update the underlying database record of a TemplateInfo instance.</summary>
		void Update(TemplateInfo obj);
		
		/// <summary>Delete the underlying database record of a TemplateInfo instance.</summary>
		void Delete(TemplateInfo obj);
		
        /// <summary>Deletes <see cref="TemplateInfo"/> instances by <see cref="TemplateInfo.Name"/>.</summary>
		int DeleteByName(String name);
		
        /// <summary>Deletes <see cref="TemplateInfo"/> instances by <see cref="TemplateInfo.Type"/>.</summary>
		int DeleteByType(Int32? type);
		
        /// <summary>Deletes <see cref="TemplateInfo"/> instances by <see cref="TemplateInfo.TemplateCode"/>.</summary>
		int DeleteByTemplateCode(String templateCode);
		
        /// <summary>Deletes <see cref="TemplateInfo"/> instances by <see cref="TemplateInfo.CreateTime"/>.</summary>
		int DeleteByCreateTime(DateTime? createTime);
		
        /// <summary>Deletes <see cref="TemplateInfo"/> instances by <see cref="TemplateInfo.CreateUserID"/>.</summary>
		int DeleteByCreateUserID(Int64? createUserID);
		
        /// <summary>Deletes <see cref="TemplateInfo"/> instances by <see cref="TemplateInfo.ModifyTime"/>.</summary>
		int DeleteByModifyTime(DateTime? modifyTime);
		
        /// <summary>Deletes <see cref="TemplateInfo"/> instances by <see cref="TemplateInfo.ModifyUserID"/>.</summary>
		int DeleteByModifyUserID(Int64? modifyUserID);
		
        /// <summary>Deletes <see cref="TemplateInfo"/> instances by <see cref="TemplateInfo.Status"/>.</summary>
		int DeleteByStatus(Int32? status);
		
		/// <summary>Reload the underlying database record of a TemplateInfo instance.</summary>
		void Reload(TemplateInfo obj);
		
	}

}
