//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CMS.Domain {
	
    /// <summary><c>ChannelInfo</c> Business Object.</summary>
    [Serializable]
    public partial class ChannelInfo {

        private List<ChannelInfo> m_childs = new List<ChannelInfo>(); 

        //子频道列表
        public IList<ChannelInfo> Childs
        {
            get {
                return m_childs;
            }
            set {
                if (value != null) {
                    m_childs.Clear();
                    m_childs.AddRange(value);
                }
            }
        }
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; 
            }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region ParentChannelID

        private Int64? m_parentChannelID = 0;
		
		/// <summary>Gets or sets ParentChannelID</summary>
        public Int64? ParentChannelID {
        	get { return m_parentChannelID; }
        	set { m_parentChannelID = value;}        
        }
		
	    #endregion
		
        #region Name

        private String m_name;
		
		/// <summary>Gets or sets Name</summary>
        [DisplayName("栏目名称")]
        [Required(ErrorMessage = "栏目名称不能为空")]
        [StringLength(512, ErrorMessage = "栏目名称不能超过512个字符")]
        public String Name {
        	get { return m_name; }
        	set { m_name = value;}        
        }
		
	    #endregion
		
        #region EnName

        private String m_enName;
		
		/// <summary>Gets or sets EnName</summary>
        [DisplayName("栏目英文名称")]
        [Required(ErrorMessage = "栏目英文名称不能为空")]
        [StringLength(512, ErrorMessage = "栏目英文名称不能超过512个字符")]
        public String EnName {
        	get { return m_enName; }
        	set { m_enName = value;}        
        }
		
	    #endregion
		
        #region Type

        private Int32 m_type;
		
		/// <summary>Gets or sets Type</summary>
        public Int32 Type {
        	get { return m_type; }
        	set { m_type = value;}        
        }
		
	    #endregion
		
        #region Sort

        private Int32 m_sort;
		
		/// <summary>Gets or sets Sort</summary>
        public Int32 Sort {
        	get { return m_sort; }
        	set { m_sort = value;}        
        }
		
	    #endregion
		
        #region ChannelUrlPart

        private String m_channelUrlPart;
		
		/// <summary>Gets or sets ChannelUrlPart</summary>
        [DisplayName("栏目URL")]
        [StringLength(512, ErrorMessage = "栏目URL不能超过512个字符")]
        public String ChannelUrlPart {
        	get { return m_channelUrlPart; }
        	set { m_channelUrlPart = value;}        
        }
		
	    #endregion
		
        #region Keyword

        private String m_keyword;
		
		/// <summary>Gets or sets Keyword</summary>
        [DisplayName("关键字")]
        [StringLength(200, ErrorMessage = "关键字不能超过200个字符")]
        public String Keyword {
        	get { return m_keyword; }
        	set { m_keyword = value;}        
        }
		
	    #endregion
		
        #region Description

        private String m_description;
		
		/// <summary>Gets or sets Description</summary>
        [DisplayName("栏目描述")]
        public String Description {
        	get { return m_description; }
        	set { m_description = value;}        
        }
		
	    #endregion
		
        #region TemplateID

        private Int64 m_templateID = 0;
		
		/// <summary>Gets or sets TemplateID</summary>
        [DisplayName("栏目模板")]
        [Range(-1, Int64.MaxValue, ErrorMessage = "请选择正确的栏目模板")]  
        public Int64 TemplateID {
        	get { return m_templateID; }
        	set { m_templateID = value;}        
        }
		
	    #endregion
		
        #region ListTemplateID

        private Int64? m_listTemplateID = 0;
		
		/// <summary>Gets or sets ListTemplateID</summary>
        [DisplayName("栏目列表页模板")]
        [Range(-1, Int64.MaxValue, ErrorMessage = "请选择正确的栏目列表页模板")]  
        public Int64? ListTemplateID {
        	get { return m_listTemplateID; }
        	set { m_listTemplateID = value;}        
        }
		
	    #endregion
		
        #region PagerID

        private Int32? m_pagerID;
		
		/// <summary>Gets or sets PagerID</summary>
        public Int32? PagerID {
        	get { return m_pagerID; }
        	set { m_pagerID = value;}        
        }
		
	    #endregion
		
        #region ContentTemplateID

        private Int64? m_contentTemplateID;
		
		/// <summary>Gets or sets ContentTemplateID</summary>
        public Int64? ContentTemplateID {
        	get { return m_contentTemplateID; }
        	set { m_contentTemplateID = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64 m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64 CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		
        #region ModifyTime

        private DateTime m_modifyTime;
		
		/// <summary>Gets or sets ModifyTime</summary>
        public DateTime ModifyTime {
        	get { return m_modifyTime; }
        	set { m_modifyTime = value;}        
        }
		
	    #endregion
		
        #region ModifyUserID

        private Int64 m_modifyUserID;
		
		/// <summary>Gets or sets ModifyUserID</summary>
        public Int64 ModifyUserID {
        	get { return m_modifyUserID; }
        	set { m_modifyUserID = value;}        
        }
		
	    #endregion
		
        #region Status

        private Int32 m_status;
		
		/// <summary>Gets or sets Status</summary>
        [DisplayName("栏目状态")]
        [Range(0, int.MaxValue, ErrorMessage = "请输入大于等于0的数")]  
        public Int32 Status {
        	get { return m_status; }
        	set { m_status = value;}        
        }
		
	    #endregion

        private string m_templateName = "";
        /// <summary>
        /// 模板名称
        /// </summary>
        public string TemplateName
        {
            get { return m_templateName; }
            set { m_templateName = value; }
        }

        private string m_listtemplateName = "";
        /// <summary>
        /// 列表页模板名称
        /// </summary>
        public string ListTemplateName
        {
            get { return m_listtemplateName; }
            set { m_listtemplateName = value; }
        }

        private string m_contenttemplateName = "";
        /// <summary>
        /// 内容页模板名称
        /// </summary>
        public string ContentTemplateName
        {
            get { return m_contenttemplateName; }
            set { m_contenttemplateName = value; }
        }
	}
	
}
