//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>ChannelPrivilege</c> Business Object.</summary>
    [Serializable]
    public partial class ChannelPrivilege {
        
        #region ID

        private Int32 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int32 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region RoleID

        private Int64 m_roleID;
		
		/// <summary>Gets or sets RoleID</summary>
        public Int64 RoleID {
        	get { return m_roleID; }
        	set { m_roleID = value;}        
        }
		
	    #endregion
		
        #region ChannelID

        private Int64 m_channelID;
		
		/// <summary>Gets or sets ChannelID</summary>
        public Int64 ChannelID {
        	get { return m_channelID; }
        	set { m_channelID = value;}        
        }
		
	    #endregion
		
        #region IsBrowse

        private Boolean m_isBrowse;
		
		/// <summary>Gets or sets IsBrowse</summary>
        public Boolean IsBrowse {
        	get { return m_isBrowse; }
        	set { m_isBrowse = value;}        
        }
		
	    #endregion
		
        #region AddAuth

        private Boolean m_addAuth;
		
		/// <summary>Gets or sets AddAuth</summary>
        public Boolean AddAuth {
        	get { return m_addAuth; }
        	set { m_addAuth = value;}        
        }
		
	    #endregion
		
        #region EditAuth

        private Boolean m_editAuth;
		
		/// <summary>Gets or sets EditAuth</summary>
        public Boolean EditAuth {
        	get { return m_editAuth; }
        	set { m_editAuth = value;}        
        }
		
	    #endregion
		
        #region DelAuth

        private Boolean m_delAuth;
		
		/// <summary>Gets or sets DelAuth</summary>
        public Boolean DelAuth {
        	get { return m_delAuth; }
        	set { m_delAuth = value;}        
        }
		
	    #endregion
		
        #region AuditingAuth

        private Boolean m_auditingAuth;
		
		/// <summary>Gets or sets AuditingAuth</summary>
        public Boolean AuditingAuth {
        	get { return m_auditingAuth; }
        	set { m_auditingAuth = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64 m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64 CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		

	}
	
}
