//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>DataBlock</c> Business Object.</summary>
    [Serializable]
    public partial class DataBlock {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region BlockName

        private String m_blockName;
		
		/// <summary>Gets or sets BlockName</summary>
        public String BlockName {
        	get { return m_blockName; }
        	set { m_blockName = value;}        
        }
		
	    #endregion
		
        #region EnName

        private String m_enName;
		
		/// <summary>Gets or sets EnName</summary>
        public String EnName {
        	get { return m_enName; }
        	set { m_enName = value;}        
        }
		
	    #endregion
		
        #region Type

        private Int16 m_type;
		
		/// <summary>Gets or sets Type</summary>
        public Int16 Type {
        	get { return m_type; }
        	set { m_type = value;}        
        }
		
	    #endregion
		
        #region RowCount

        private Int32 m_rowCount;
		
		/// <summary>Gets or sets RowCount</summary>
        public Int32 RowCount {
        	get { return m_rowCount; }
        	set { m_rowCount = value;}        
        }
		
	    #endregion
		
        #region OrderByField

        private String m_orderByField;
		
		/// <summary>Gets or sets OrderByField</summary>
        public String OrderByField {
        	get { return m_orderByField; }
        	set { m_orderByField = value;}        
        }
		
	    #endregion
		
        #region Where

        private String m_where;
		
		/// <summary>Gets or sets Where</summary>
        public String Where {
        	get { return m_where; }
        	set { m_where = value;}        
        }
		
	    #endregion
		
        #region Status

        private Int16 m_status =1;
		
		/// <summary>Gets or sets Status</summary>
        public Int16 Status {
        	get { return m_status; }
        	set { m_status = value;}        
        }
		
	    #endregion
		
        #region TemplateID

        private Int64 m_templateID;
		
		/// <summary>Gets or sets TemplateID</summary>
        public Int64 TemplateID {
        	get { return m_templateID; }
        	set { m_templateID = value;}        
        }
		
	    #endregion
		
        #region Note

        private String m_note;
		
		/// <summary>Gets or sets Note</summary>
        public String Note {
        	get { return m_note; }
        	set { m_note = value;}        
        }
		
	    #endregion
		
        #region AddDate

        private DateTime m_addDate;
		
		/// <summary>Gets or sets AddDate</summary>
        public DateTime AddDate {
        	get { return m_addDate; }
        	set { m_addDate = value;}        
        }
		
	    #endregion

        /// <summary>
        /// Ä£°åÃû³Æ
        /// </summary>
        public string TemplateName
        {
            get;
            set;
        }

	}
	
}
