/*
insert license info here
*/
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CMS.Domain
{
    /// <summary>
    ///	Generated by MyGeneration using the IBatis Object Mapping template
    /// </summary>
    [Serializable]
    public sealed class download_password
    {
        public Int32 ID { get; set; }
        public Int32 FileID { get; set; }
        public string password { get; set; }
        public DateTime send_time { get; set; }
        public Int32 send_userid { get; set; }
    }
}