/*
insert license info here
*/
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CMS.Domain
{
    /// <summary>
    ///	Generated by MyGeneration using the IBatis Object Mapping template
    /// </summary>
    [Serializable]
    public sealed class FeedBack
    {
        #region Private Members
        private bool m_isChanged;
        private bool m_isDeleted;
        private Int64 m_id;
        private string m_titile;
        private string m_message;
        private string m_username;
        private string m_email;
        private string m_gender;
        private string m_ip;
        private DateTime m_createtime;
        private int m_messagetype;
        private string m_replymessae;
        private Int64 m_replyuserid;
        private DateTime m_replytime;
        private int m_status;
        #endregion

        #region Default ( Empty ) Class Constuctor
        /// <summary>
        /// default constructor
        /// </summary>
        public FeedBack()
        {
            m_id = 0;
            m_titile = null;
            m_message = null;
            m_username = null;
            m_email = null;
            m_gender = null;
            m_ip = null;
            m_createtime = new DateTime();
            m_messagetype = 0;
            m_replymessae = null;
            m_replyuserid = 0;
            m_replytime = new DateTime();
            m_status = 0;
        }
        #endregion // End of Default ( Empty ) Class Constuctor

        #region Public Properties

        /// <summary>
        /// 
        /// </summary>		
        public Int64 Id
        {
            get { return m_id; }
            set { m_isChanged |= (m_id != value); m_id = value; }
        }

        [DisplayName("标题")]
        [Required(ErrorMessage = "标题不能为空")]
        [StringLength(512, ErrorMessage = "标题不能超过512个字符")]	
        public string Titile
        {
            get { return m_titile; }
        	set { m_titile = value;}      
        }

        [DisplayName("内容")]
        [Required(ErrorMessage = "内容不能为空")]	
        public string Message
        {
            get { return m_message; }
        	set { m_message = value;}  
        }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名不能为空")]
        [StringLength(128, ErrorMessage = "姓名不能超过128个字符")]		
        public string UserName
        {
            get { return m_username; }
            set { m_username = value; } 
        }

        [DisplayName("电邮")]
        [Required(ErrorMessage = "电邮不能为空")]
        [StringLength(128, ErrorMessage = "电邮不能超过128个字符")]	
        [RegularExpression("^[\\w-]+(\\.[\\w-]+)*@[\\w-]+(\\.[\\w-]+)+$",ErrorMessage="电子邮箱格式不正确")]
        public string Email
        {
            get { return m_email; }

            set { m_email = value; } 
        }

        /// <summary>
        /// 男，女
        /// </summary>		
        public string Gender
        {
            get { return m_gender; }
            set
            {
                if (value != null && value.Length > 2)
                    throw new ArgumentOutOfRangeException("Invalid value for Gender", value, value.ToString());

                m_isChanged |= (m_gender != value); m_gender = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string Ip
        {
            get { return m_ip; }
            set
            {
                if (value != null && value.Length > 32)
                    throw new ArgumentOutOfRangeException("Invalid value for Ip", value, value.ToString());

                m_isChanged |= (m_ip != value); m_ip = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime CreateTime
        {
            get { return m_createtime; }
            set { m_isChanged |= (m_createtime != value); m_createtime = value; }
        }

        /// <summary>
        /// 1=建议 2=业务 3=投诉
        /// </summary>		
        public int MessageType
        {
            get { return m_messagetype; }
            set { m_isChanged |= (m_messagetype != value); m_messagetype = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public string ReplyMessae
        {
            get { return m_replymessae; }
            set
            {
                if (value != null && value.Length > 1073741823)
                    throw new ArgumentOutOfRangeException("Invalid value for ReplyMessae", value, value.ToString());

                m_isChanged |= (m_replymessae != value); m_replymessae = value;
            }
        }

        /// <summary>
        /// 
        /// </summary>		
        public Int64 ReplyUserid
        {
            get { return m_replyuserid; }
            set { m_isChanged |= (m_replyuserid != value); m_replyuserid = value; }
        }

        /// <summary>
        /// 
        /// </summary>		
        public DateTime ReplyTime
        {
            get { return m_replytime; }
            set { m_isChanged |= (m_replytime != value); m_replytime = value; }
        }

        /// <summary>
        /// 0=未审核 1=审核通过 2=已回复
        /// 0=客户预定 1=未预定 3=已预定
        /// </summary>		
        public int Status
        {
            get { return m_status; }
            set { m_isChanged |= (m_status != value); m_status = value; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsChanged
        {
            get { return m_isChanged; }
        }

        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public bool IsDeleted
        {
            get { return m_isDeleted; }
        }

        #endregion


        [DisplayName("验证码")]
        [Required(ErrorMessage = "验证码不能为空")]
        public string VerifyCode
        {
            get;
            set;
        }

        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public void MarkAsDeleted()
        {
            m_isDeleted = true;
            m_isChanged = true;
        }

        #endregion

        public String Mobile { get; set; }

        public String Address { get; set; }

        public String CompanyName { get; set; }

        /// <summary>
        /// 桌数目
        /// </summary>
        public Int16 DeskCount { get; set; }

        /// <summary>
        /// 预定的时间
        /// </summary>
        public String PreDate { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        public String Remarks { get; set; }
    }
}