//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>FileStore</c> Business Object.</summary>
    [Serializable]
    public partial class FileStore {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region ChannelID

        private Int64? m_channelID;
		
		/// <summary>Gets or sets ChannelID</summary>
        public Int64? ChannelID {
        	get { return m_channelID; }
        	set { m_channelID = value;}        
        }
		
	    #endregion
		
        #region DocID

        private Int64? m_docID;
		
		/// <summary>Gets or sets DocID</summary>
        public Int64? DocID {
        	get { return m_docID; }
        	set { m_docID = value;}        
        }
		
	    #endregion
		
        #region ExtName

        private String m_extName;
		
		/// <summary>Gets or sets ExtName</summary>
        public String ExtName {
        	get { return m_extName; }
        	set { m_extName = value;}        
        }
		
	    #endregion
		
        #region LocalPath

        private String m_localPath;
		
		/// <summary>Gets or sets LocalPath</summary>
        public String LocalPath {
        	get { return m_localPath; }
        	set { m_localPath = value;}        
        }
		
	    #endregion
		
        #region URL

        private String m_uRL;
		
		/// <summary>Gets or sets URL</summary>
        public String URL {
        	get { return m_uRL; }
        	set { m_uRL = value;}        
        }
		
	    #endregion
		
        #region FileSize

        private Int32 m_fileSize;
		
		/// <summary>Gets or sets FileSize</summary>
        public Int32 FileSize {
        	get { return m_fileSize; }
        	set { m_fileSize = value;}        
        }
		
	    #endregion
		
        #region Md5

        private String m_md5;
		
		/// <summary>Gets or sets Md5</summary>
        public String Md5 {
        	get { return m_md5; }
        	set { m_md5 = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion

        #region PublicTime

        private DateTime m_publicTime;

        /// <summary>Gets or sets CreateTime</summary>
        public DateTime PublicTime
        {
            get { return m_publicTime; }
            set { m_publicTime = value; }
        }

        #endregion
		
        #region CreateUserID

        private Int64 m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64 CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		

	}
	
}
