//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CMS.Domain {
	
    /// <summary><c>GlobalVariable</c> Business Object.</summary>
    [Serializable]
    public partial class GlobalVariable {
        
        #region GlobalID

        private Int64 m_globalID;
		
		/// <summary>Gets or sets GlobalID</summary>
        public Int64 GlobalID {
        	get { return m_globalID; }
        	set { m_globalID = value;}        
        }
		
	    #endregion
		
        #region GlobalName

        private String m_globalName;
		
		/// <summary>Gets or sets GlobalName</summary>
        [DisplayName("全局变量名称")]
        [Required(ErrorMessage = "全局变量名称不能为空")]
        [StringLength(50, ErrorMessage = "全局变量名称不能超过50个字符")]
        public String GlobalName {
        	get { return m_globalName; }
        	set { m_globalName = value;}        
        }
		
	    #endregion
		
        #region EnName

        private String m_enName;
		
		/// <summary>Gets or sets EnName</summary>
        [DisplayName("英文名称")]
        [Required(ErrorMessage = "英文名称不能为空")]
        [StringLength(100, ErrorMessage = "英文名称不能超过100个字符")]
        public String EnName {
        	get { return m_enName; }
        	set { m_enName = value;}        
        }
		
	    #endregion
		
        #region Content

        private String m_content = "";
		
		/// <summary>Gets or sets Content</summary>
        public String Content {
        	get { return m_content; }
        	set { m_content = value;}        
        }
		
	    #endregion
		
        #region IsInclude

        private Boolean m_isInclude =false;
		
		/// <summary>Gets or sets IsInclude</summary>
        public Boolean IsInclude {
        	get { return m_isInclude; }
        	set { m_isInclude = value;}        
        }
		
	    #endregion
		
        #region AddDate

        private DateTime m_addDate;
		
		/// <summary>Gets or sets AddDate</summary>
        public DateTime AddDate {
        	get { return m_addDate; }
        	set { m_addDate = value;}        
        }
		
	    #endregion
		
        #region IsDeleted

        private Int16 m_isDeleted;
		
		/// <summary>Gets or sets IsDeleted</summary>
        public Int16 IsDeleted {
        	get { return m_isDeleted; }
        	set { m_isDeleted = value;}        
        }
		
	    #endregion
		

	}
	
}
