//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CMS.Domain {
	
    /// <summary><c>JobType</c> Business Object.</summary>
    [Serializable]
    public partial class JobType {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region Name

        private String m_name;

        [DisplayName("类型名称")]
        [Required(ErrorMessage = "类型名称不能为空")]
        [StringLength(30, ErrorMessage = "类型名称不能超过30个字符")]	
        public String Name {
        	get { return m_name; }
        	set { m_name = value;}        
        }
		
	    #endregion
		
        #region Description

        private String m_description;

        [DisplayName("类型描述")]
        [Required(ErrorMessage = "类型描述不能为空")]
        [StringLength(500, ErrorMessage = "类型描述不能超过500个字符")]	
        public String Description {
        	get { return m_description; }
        	set { m_description = value;}        
        }
		
	    #endregion
		

	}
	
}
