//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>ModuleInfo</c> Business Object.</summary>
    [Serializable]
    public partial class ModuleInfo {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region PID

        private Int64 m_pID;
		
		/// <summary>Gets or sets PID</summary>
        public Int64 PID {
        	get { return m_pID; }
        	set { m_pID = value;}        
        }
		
	    #endregion
		
        #region ModuleType

        private Int16 m_moduleType;
		
		/// <summary>Gets or sets ModuleType</summary>
        public Int16 ModuleType {
        	get { return m_moduleType; }
        	set { m_moduleType = value;}        
        }
		
	    #endregion
		
        #region ModuleName

        private String m_moduleName;
		
		/// <summary>Gets or sets ModuleName</summary>
        public String ModuleName {
        	get { return m_moduleName; }
        	set { m_moduleName = value;}        
        }
		
	    #endregion
		
        #region ModuleUrl

        private String m_moduleUrl;
		
		/// <summary>Gets or sets ModuleUrl</summary>
        public String ModuleUrl {
        	get { return m_moduleUrl; }
        	set { m_moduleUrl = value;}        
        }
		
	    #endregion
		
        #region Description

        private String m_description;
		
		/// <summary>Gets or sets Description</summary>
        public String Description {
        	get { return m_description; }
        	set { m_description = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64 m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64 CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		
        #region SortID

        private Int32 m_sortID;
		
		/// <summary>Gets or sets SortID</summary>
        public Int32 SortID {
        	get { return m_sortID; }
        	set { m_sortID = value;}        
        }
		
	    #endregion
		
        #region Status

        private Int16 m_status;
		
		/// <summary>Gets or sets Status</summary>
        public Int16 Status {
        	get { return m_status; }
        	set { m_status = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		

	}
	
}
