//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CMS.Domain {
	
    /// <summary><c>NewsDoc</c> Business Object.</summary>
    [Serializable]
    public partial class NewsDoc {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region ChannelID

        private Int64 m_channelID;
		
		/// <summary>Gets or sets ChannelID</summary>
        public Int64 ChannelID {
        	get { return m_channelID; }
        	set { m_channelID = value;}        
        }
		
	    #endregion
		
        #region SpecialID

        private Int64? m_specialID;
		
		/// <summary>Gets or sets SpecialID</summary>
        public Int64? SpecialID {
        	get { return m_specialID; }
        	set { m_specialID = value;}        
        }
		
	    #endregion
		
        #region Title

        private String m_title;
		
		/// <summary>Gets or sets Title</summary>
        [DisplayName("文章标题")]
        [Required(ErrorMessage = "文章标题不能为空")]
        public String Title {
        	get { return m_title; }
        	set { m_title = value;}        
        }
		
	    #endregion
		
        #region SubTitle

        private String m_subTitle;
		
		/// <summary>Gets or sets SubTitle</summary>
        public String SubTitle {
        	get { return m_subTitle; }
        	set { m_subTitle = value;}        
        }
		
	    #endregion
		
        #region TitleColor

        private String m_titleColor;
		
		/// <summary>Gets or sets TitleColor</summary>
        public String TitleColor {
        	get { return m_titleColor; }
        	set { m_titleColor = value;}        
        }
		
	    #endregion
		
        #region Author

        private String m_author;
		
		/// <summary>Gets or sets Author</summary>
        public String Author {
        	get { return m_author; }
        	set { m_author = value;}        
        }
		
	    #endregion
		
        #region PublicTime

        private DateTime? m_publicTime;
		
		/// <summary>Gets or sets PublicTime</summary>
        [DisplayName("发表时间")]
        [Required(ErrorMessage = "发表时间不能为空")]
        public DateTime? PublicTime {
        	get { return m_publicTime; }
        	set { m_publicTime = value;}        
        }
		
	    #endregion
		
        #region Content

        private String m_content;
		
		/// <summary>Gets or sets Content</summary>
        public String Content {
        	get { return m_content; }
        	set { m_content = value;}        
        }
		
	    #endregion
		
        #region Summary

        private String m_summary;
		
		/// <summary>Gets or sets Summary</summary>
        public String Summary {
        	get { return m_summary; }
        	set { m_summary = value;}        
        }
		
	    #endregion
		
        #region IsTop

        private Boolean m_isTop;
		
		/// <summary>Gets or sets IsTop</summary>
        public Boolean IsTop {
        	get { return m_isTop; }
        	set { m_isTop = value;}        
        }
		
	    #endregion
		
        #region IsRecommend

        private Boolean m_isRecommend;
		
		/// <summary>Gets or sets IsRecommend</summary>
        public Boolean IsRecommend {
        	get { return m_isRecommend; }
        	set { m_isRecommend = value;}        
        }
		
	    #endregion
		
        #region IsBold

        private Boolean m_isBold;
		
		/// <summary>Gets or sets IsBold</summary>
        public Boolean IsBold {
        	get { return m_isBold; }
        	set { m_isBold = value;}        
        }
		
	    #endregion
		
        #region Tags

        private String m_tags;
		
		/// <summary>Gets or sets Tags</summary>
        public String Tags {
        	get { return m_tags; }
        	set { m_tags = value;}        
        }
		
	    #endregion
		
        #region Linkurl

        private String m_linkurl;
		
		/// <summary>Gets or sets Linkurl</summary>
        public String Linkurl {
        	get { return m_linkurl; }
        	set { m_linkurl = value;}        
        }
		
	    #endregion
		
        #region SmallImageUrl

        private String m_smallImageUrl;
		
		/// <summary>Gets or sets SmallImageUrl</summary>
        public String SmallImageUrl {
        	get { return m_smallImageUrl; }
        	set { m_smallImageUrl = value;}        
        }
		
	    #endregion
		
        #region Source

        private String m_source;
		
		/// <summary>Gets or sets Source</summary>
        public String Source {
        	get { return m_source; }
        	set { m_source = value;}        
        }
		
	    #endregion
		
        #region ClickCount

        private Int32 m_clickCount;
		
		/// <summary>Gets or sets ClickCount</summary>
        public Int32 ClickCount {
        	get { return m_clickCount; }
        	set { m_clickCount = value;}        
        }
		
	    #endregion
		
        #region Status

        private Int32 m_status;
		
		/// <summary>Gets or sets Status</summary>
        public Int32 Status {
        	get { return m_status; }
        	set { m_status = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64? m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64? CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		
        #region CreateUserIP

        private String m_createUserIP;
		
		/// <summary>Gets or sets CreateUserIP</summary>
        public String CreateUserIP {
        	get { return m_createUserIP; }
        	set { m_createUserIP = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime? m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime? CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region AuditUserID

        private Int64? m_auditUserID;
		
		/// <summary>Gets or sets AuditUserID</summary>
        public Int64? AuditUserID {
        	get { return m_auditUserID; }
        	set { m_auditUserID = value;}        
        }
		
	    #endregion
		
        #region AuditTime

        private DateTime? m_auditTime;
		
		/// <summary>Gets or sets AuditTime</summary>
        public DateTime? AuditTime {
        	get { return m_auditTime; }
        	set { m_auditTime = value;}        
        }
		
	    #endregion
		
        #region ModifyUserID

        private Int64? m_modifyUserID;
		
		/// <summary>Gets or sets ModifyUserID</summary>
        public Int64? ModifyUserID {
        	get { return m_modifyUserID; }
        	set { m_modifyUserID = value;}        
        }
		
	    #endregion
		
        #region ModifyTime

        private DateTime? m_modifyTime;
		
		/// <summary>Gets or sets ModifyTime</summary>
        public DateTime? ModifyTime {
        	get { return m_modifyTime; }
        	set { m_modifyTime = value;}        
        }
		
	    #endregion
		
        #region ModifyUserIP

        private String m_modifyUserIP;
		
		/// <summary>Gets or sets ModifyUserIP</summary>
        public String ModifyUserIP {
        	get { return m_modifyUserIP; }
        	set { m_modifyUserIP = value;}        
        }
		
	    #endregion
		
        #region IsAuditing

        private Int16 m_isAuditing;
		
		/// <summary>Gets or sets IsAuditing</summary>
        public Int16 IsAuditing {
        	get { return m_isAuditing; }
        	set { m_isAuditing = value;}        
        }
		
	    #endregion
		
        #region IsDelete

        private Int16 m_isDelete;
		
		/// <summary>Gets or sets IsDelete</summary>
        public Int16 IsDelete {
        	get { return m_isDelete; }
        	set { m_isDelete = value;}        
        }
		
	    #endregion

        /// <summary>
        /// 栏目名称
        /// </summary>
        public string ChannelName
        {
            get;
            set;
        }

        /// <summary>
        /// 审核状态
        /// </summary>
        public string AuditingStats
        {
            get;
            set;
        }

        private int? _sortID = 0;
        /// <summary>
        /// 排序ID
        /// </summary>
        public int? SortID
        {
            get
            {
                return _sortID;
            }
            set
            {
                _sortID = value;
            }
        }

        private int? _SpecialChannelID = 0;
        /// <summary>
        /// 专题栏目ID
        /// </summary>
        public int? SpecialChannelID
        {
            get
            {
                return _SpecialChannelID;
            }
            set
            {
                _SpecialChannelID = value;
            }
        }
	}
	
}
