//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>PagerInfo</c> Business Object.</summary>
    [Serializable]
    public partial class PagerInfo {
        
        #region PageID

        private Int32 m_pageID;
		
		/// <summary>Gets or sets PageID</summary>
        public Int32 PageID {
        	get { return m_pageID; }
        	set { m_pageID = value;}        
        }
		
	    #endregion
		
        #region DataType

        private Int32? m_dataType;
		
		/// <summary>Gets or sets DataType</summary>
        public Int32? DataType {
        	get { return m_dataType; }
        	set { m_dataType = value;}        
        }
		
	    #endregion
		
        #region Where

        private String m_where;
		
		/// <summary>Gets or sets Where</summary>
        public String Where {
        	get { return m_where; }
        	set { m_where = value;}        
        }
		
	    #endregion
		
        #region OrderBy

        private String m_orderBy;
		
		/// <summary>Gets or sets OrderBy</summary>
        public String OrderBy {
        	get { return m_orderBy; }
        	set { m_orderBy = value;}        
        }
		
	    #endregion
		
        #region PageSize

        private Int32? m_pageSize;
		
		/// <summary>Gets or sets PageSize</summary>
        public Int32? PageSize {
        	get { return m_pageSize; }
        	set { m_pageSize = value;}        
        }
		
	    #endregion
		
        #region AddDate

        private DateTime? m_addDate;
		
		/// <summary>Gets or sets AddDate</summary>
        public DateTime? AddDate {
        	get { return m_addDate; }
        	set { m_addDate = value;}        
        }
		
	    #endregion

        public string DataTypeName
        {
            get;
            set;
        }

        public string PagerName
        { get; set; }
	}
	
}
