//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CMS.Domain {
	
    /// <summary><c>RecommedPosition</c> Business Object.</summary>
    [Serializable]
    public partial class RecommedPosition {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region Name

        private String m_name;
		
		/// <summary>Gets or sets Name</summary>
        [DisplayName("位置名称")]
        [Required(ErrorMessage = "位置名称不能为空")]
        [StringLength(256, ErrorMessage = "位置名称不能超过256个字符")]
        public String Name {
        	get { return m_name; }
        	set { m_name = value;}        
        }
		
	    #endregion
		
        #region ChannelID

        private Int64 m_channelID=0;
		
		/// <summary>Gets or sets ChannelID</summary>
        public Int64 ChannelID {
        	get { return m_channelID; }
        	set { m_channelID = value;}        
        }
		
	    #endregion
		
        #region LocationType

        private Int32 m_locationType;
		
		/// <summary>Gets or sets LocationType</summary>
        public Int32 LocationType {
        	get { return m_locationType; }
        	set { m_locationType = value;}        
        }
		
	    #endregion
		
        #region Summary

        private String m_summary;
		
		/// <summary>Gets or sets Summary</summary>
        [DisplayName("位置说明")]
        [StringLength(512, ErrorMessage = "位置说明不能超过512个字符")]
        public String Summary {
        	get { return m_summary; }
        	set { m_summary = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion

        public string ChannelName
        {
            get;
            set;
        }

        public string LocationTypeName
        {
            get;
            set;
        }
	}
	
}
