//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>RecommedInfoList</c> Business Object.</summary>
    [Serializable]
    public partial class RecommedInfoList {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region LocationID

        private Int64? m_locationID;
		
		/// <summary>Gets or sets LocationID</summary>
        public Int64? LocationID {
        	get { return m_locationID; }
        	set { m_locationID = value;}        
        }
		
	    #endregion
		
        #region DocID

        private Int64? m_docID;
		
		/// <summary>Gets or sets DocID</summary>
        public Int64? DocID {
        	get { return m_docID; }
        	set { m_docID = value;}        
        }
		
	    #endregion
		
        #region Title

        private String m_title;
		
		/// <summary>Gets or sets Title</summary>
        public String Title {
        	get { return m_title; }
        	set { m_title = value;}        
        }
		
	    #endregion
		
        #region SmallPicUrl

        private String m_smallPicUrl;
		
		/// <summary>Gets or sets SmallPicUrl</summary>
        public String SmallPicUrl {
        	get { return m_smallPicUrl; }
        	set { m_smallPicUrl = value;}        
        }
		
	    #endregion
		
        #region BigPicUrl

        private String m_bigPicUrl;
		
		/// <summary>Gets or sets BigPicUrl</summary>
        public String BigPicUrl {
        	get { return m_bigPicUrl; }
        	set { m_bigPicUrl = value;}        
        }
		
	    #endregion
		
        #region Summary

        private String m_summary;
		
		/// <summary>Gets or sets Summary</summary>
        public String Summary {
        	get { return m_summary; }
        	set { m_summary = value;}        
        }
		
	    #endregion
		
        #region LinkUrl

        private String m_linkUrl;
		
		/// <summary>Gets or sets LinkUrl</summary>
        public String LinkUrl {
        	get { return m_linkUrl; }
        	set { m_linkUrl = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64? m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64? CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime? m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime? CreateTime {
        	get { return m_createTime == null ? DateTime.Now : m_createTime.Value; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region SortID

        private Int32 m_sortID;
		
		/// <summary>Gets or sets SortID</summary>
        public Int32 SortID {
        	get { return m_sortID; }
        	set { m_sortID = value;}        
        }
		
	    #endregion
		
        #region Status

        private Int32 m_status;
		
		/// <summary>Gets or sets Status</summary>
        public Int32 Status {
        	get { return m_status; }
        	set { m_status = value;}        
        }
		
	    #endregion
		

	}
	
}
