//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CMS.Domain {
	
    /// <summary><c>Resume</c> Business Object.</summary>
    [Serializable]
    public partial class Resume {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region PositionID

        private Int64 m_positionID;
		
		/// <summary>Gets or sets PositionID</summary>
        public Int64 PositionID {
        	get { return m_positionID; }
        	set { m_positionID = value;}        
        }
		
	    #endregion

        #region JobInfomation

        private JobInfo m_jobInfo;

        /// <summary>Gets or sets PositionID</summary>
        public JobInfo JobInfomation
        {
            get { return m_jobInfo; }
            set { m_jobInfo = value; }
        }

        #endregion
		
        #region Name

        private String m_name;

        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名不能为空")]
        [StringLength(128, ErrorMessage = "姓名不能超过128个字符")]	
        public String Name {
        	get { return m_name; }
        	set { m_name = value;}        
        }
		
	    #endregion
		
        #region Mobile

        private String m_mobile;
        [DisplayName("手机")]
        [Required(ErrorMessage = "手机号不能为空")]
        [RegularExpression("^(1(([35][0-9])|(47)|[8][0126789]))\\d{8}$", ErrorMessage = "手机号码格式不正确")]	
        public String Mobile {
        	get { return m_mobile; }
        	set { m_mobile = value;}        
        }
		
	    #endregion
		
        #region Telphone

        private String m_telphone;

        [DisplayName("电话")]
        [Required(ErrorMessage = "电话号不能为空")]
        [RegularExpression("(^(\\d{2,4}[-_－—]?)?\\d{3,8}([-_－—]?\\d{3,8})?([-_－—]?\\d{1,7})?$)|(^0?1[35]\\d{9}$)", ErrorMessage = "电话号码格式不正确")]	
        public String Telphone {
        	get { return m_telphone; }
        	set { m_telphone = value;}        
        }
		
	    #endregion
		
        #region Text

        private String m_text;

        [DisplayName("内容")]
        [Required(ErrorMessage = "内容不能为空")]	
        public String Text {
        	get { return m_text; }
        	set { m_text = value;}        
        }

        [DisplayName("上传")]
        [Required(ErrorMessage = "上传不能为空")]
        [RegularExpression("^(([a-zA-Z]:)|(\\{2}\\w+)\\$?)(\\(\\w[\\w].*))+(.doc|.docx)$", ErrorMessage = "上传文件只能是doc、docx格式")]
        public String UploadFile
        {
            get;
            set;
        }

	    #endregion
		
        #region FileID

        private Int64 m_fileID;
		
		/// <summary>Gets or sets FileID</summary>
        public Int64 FileID {
        	get { return m_fileID; }
        	set { m_fileID = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region Status

        private Int32 m_status;
		
		/// <summary>1=未处理   2=通过审核   3=未通过审核</summary>
        public Int32 Status {
        	get { return m_status; }
        	set { m_status = value;}        
        }
		
	    #endregion
		
        #region ReviewUserID

        private Int64? m_reviewUserID;
		
		/// <summary>Gets or sets ReviewUserID</summary>
        public Int64? ReviewUserID {
        	get { return m_reviewUserID; }
        	set { m_reviewUserID = value;}        
        }
		
	    #endregion
		
        #region ReviewTime

        private DateTime? m_reviewTime;
		
		/// <summary>Gets or sets ReviewTime</summary>
        public DateTime? ReviewTime {
        	get { return m_reviewTime; }
        	set { m_reviewTime = value;}        
        }

        private String m_Email;

        [DisplayName("邮箱")]
        [Required(ErrorMessage = "邮箱不能为空")]
        public String Email
        {
            get { return m_Email; }
            set { m_Email = value; }
        }
	    #endregion

	}
	
}
