//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>RoleInfo</c> Business Object.</summary>
    [Serializable]
    public partial class RoleInfo {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region RoleName

        private String m_roleName;
		
		/// <summary>Gets or sets RoleName</summary>
        public String RoleName {
        	get { return m_roleName; }
        	set { m_roleName = value;}        
        }
		
	    #endregion
		
        #region Description

        private String m_description = "";
		
		/// <summary>Gets or sets Description</summary>
        public String Description {
        	get { return m_description; }
        	set { m_description = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region IsCmsAdmin

        private Int32 m_isCmsAdmin = 1;
		
		/// <summary>Gets or sets IsCmsAdmin</summary>
        public Int32 IsCmsAdmin {
        	get { return m_isCmsAdmin; }
        	set { m_isCmsAdmin = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64 m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64 CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
	}
	
}
