//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>SpecialChannel</c> Business Object.</summary>
    [Serializable]
    public partial class SpecialChannel {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region SpecialID

        private Int64 m_specialID;
		
		/// <summary>Gets or sets SpecialID</summary>
        public Int64 SpecialID {
        	get { return m_specialID; }
        	set { m_specialID = value;}        
        }
		
	    #endregion
		
        #region SubSpecialName

        private String m_subSpecialName;
		
		/// <summary>Gets or sets SubSpecialName</summary>
        public String SubSpecialName {
        	get { return m_subSpecialName; }
        	set { m_subSpecialName = value;}        
        }
		
	    #endregion
		
        #region Url

        private String m_url;
		
		/// <summary>Gets or sets Url</summary>
        public String Url {
        	get { return m_url; }
        	set { m_url = value;}        
        }
		
	    #endregion
		
        #region TemplateID

        private Int64 m_templateID;
		
		/// <summary>Gets or sets TemplateID</summary>
        public Int64 TemplateID {
        	get { return m_templateID; }
        	set { m_templateID = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64 m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64 CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		
        #region CreateTiem

        private DateTime m_createTiem;
		
		/// <summary>Gets or sets CreateTiem</summary>
        public DateTime CreateTiem {
        	get { return m_createTiem; }
        	set { m_createTiem = value;}        
        }
		
	    #endregion
		
        #region ModifyUserID

        private Int64 m_modifyUserID;
		
		/// <summary>Gets or sets ModifyUserID</summary>
        public Int64 ModifyUserID {
        	get { return m_modifyUserID; }
        	set { m_modifyUserID = value;}        
        }
		
	    #endregion
		
        #region ModifyTime

        private DateTime m_modifyTime;
		
		/// <summary>Gets or sets ModifyTime</summary>
        public DateTime ModifyTime {
        	get { return m_modifyTime; }
        	set { m_modifyTime = value;}        
        }
		
	    #endregion

        public string TemplateName
        {
            get;
            set;
        }
	}
	
}
