//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>SpecialInfo</c> Business Object.</summary>
    [Serializable]
    public partial class SpecialInfo {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region Name

        private String m_name;
		
		/// <summary>Gets or sets Name</summary>
        public String Name {
        	get { return m_name; }
        	set { m_name = value;}        
        }
		
	    #endregion
		
        #region EnName

        private String m_enName;
		
		/// <summary>Gets or sets EnName</summary>
        public String EnName {
        	get { return m_enName; }
        	set { m_enName = value;}        
        }
		
	    #endregion
		
        #region TemplateID

        private Int64 m_templateID;
		
		/// <summary>Gets or sets TemplateID</summary>
        public Int64 TemplateID {
        	get { return m_templateID; }
        	set { m_templateID = value;}        
        }
		
	    #endregion
		
        #region SmallPicUrl

        private String m_smalllPicUrl;
		
		/// <summary>Gets or sets SmallPicUrl</summary>
        public String SmallPicUrl {
        	get { return m_smalllPicUrl; }
        	set { m_smalllPicUrl = value;}        
        }
		
	    #endregion
		
        #region PicUrl

        private String m_picUrl;
		
		/// <summary>Gets or sets PicUrl</summary>
        public String PicUrl {
        	get { return m_picUrl; }
        	set { m_picUrl = value;}        
        }
		
	    #endregion
		
        #region Keyword

        private String m_keyword;
		
		/// <summary>Gets or sets Keyword</summary>
        public String Keyword {
        	get { return m_keyword; }
        	set { m_keyword = value;}        
        }
		
	    #endregion
		
        #region Description

        private String m_description;
		
		/// <summary>Gets or sets Description</summary>
        public String Description {
        	get { return m_description; }
        	set { m_description = value;}        
        }
		
	    #endregion
		
        #region Sort

        private Int32 m_sort;
		
		/// <summary>Gets or sets Sort</summary>
        public Int32 Sort {
        	get { return m_sort; }
        	set { m_sort = value;}        
        }
		
	    #endregion
		
        #region SpecialUrlPart

        private String m_specialUrlPart;
		
		/// <summary>Gets or sets SpecialUrlPart</summary>
        public String SpecialUrlPart {
        	get { return m_specialUrlPart; }
        	set { m_specialUrlPart = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion

        /// <summary>
        /// Ä£°åÃû³Æ
        /// </summary>
        public string TemplateName
        {
            get;
            set;
        }
	}
	
}
