//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>TagDefine</c> Business Object.</summary>
    [Serializable]
    public partial class TagDefine {
        
        #region Id

        private Int64 m_id;
		
		/// <summary>Gets or sets Id</summary>
        public Int64 Id {
        	get { return m_id; }
        	set { m_id = value;}        
        }
		
	    #endregion
		
        #region TagName

        private String m_tagName;
		
		/// <summary>Gets or sets TagName</summary>
        public String TagName {
        	get { return m_tagName; }
        	set { m_tagName = value;}        
        }
		
	    #endregion
		
        #region TagCode

        private String m_tagCode;
		
		/// <summary>Gets or sets TagCode</summary>
        public String TagCode {
        	get { return m_tagCode; }
        	set { m_tagCode = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64 m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64 CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		
        #region ModifyTime

        private DateTime m_modifyTime;
		
		/// <summary>Gets or sets ModifyTime</summary>
        public DateTime ModifyTime {
        	get { return m_modifyTime; }
        	set { m_modifyTime = value;}        
        }
		
	    #endregion
		
        #region ModifyUserID

        private Int64 m_modifyUserID;
		
		/// <summary>Gets or sets ModifyUserID</summary>
        public Int64 ModifyUserID {
        	get { return m_modifyUserID; }
        	set { m_modifyUserID = value;}        
        }
		
	    #endregion
		

	}
	
}
