//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>TemplateDataUseInfo</c> Business Object.</summary>
    [Serializable]
    public partial class TemplateDataUseInfo {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region MainTemplateID

        private Int64? m_mainTemplateID;
		
		/// <summary>Gets or sets MainTemplateID</summary>
        public Int64? MainTemplateID {
        	get { return m_mainTemplateID; }
        	set { m_mainTemplateID = value;}        
        }
		
	    #endregion
		
        #region TemplateID

        private Int64? m_templateID;
		
		/// <summary>Gets or sets TemplateID</summary>
        public Int64? TemplateID {
        	get { return m_templateID; }
        	set { m_templateID = value;}        
        }
		
	    #endregion
		
        #region DataBlockID

        private Int64? m_dataBlockID;
		
		/// <summary>Gets or sets DataBlockID</summary>
        public Int64? DataBlockID {
        	get { return m_dataBlockID; }
        	set { m_dataBlockID = value;}        
        }
		
	    #endregion
		

	}
	
}
