//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;

namespace CMS.Domain {
	
    /// <summary><c>TemplateInfo</c> Business Object.</summary>
    [Serializable]
    public partial class TemplateInfo {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region Name

        private String m_name;
		
		/// <summary>Gets or sets Name</summary>
        public String Name {
        	get { return m_name; }
        	set { m_name = value;}        
        }
		
	    #endregion
		
        #region Type

        private Int32? m_type;
		
		/// <summary>Gets or sets Type</summary>
        public Int32? Type {
        	get { return m_type; }
        	set { m_type = value;}        
        }
		
	    #endregion
		
        #region TemplateCode

        private String m_templateCode;
		
		/// <summary>Gets or sets TemplateCode</summary>
        public String TemplateCode {
        	get { return m_templateCode; }
        	set { m_templateCode = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime? m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime? CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64? m_createUserID;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64? CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		
        #region ModifyTime

        private DateTime? m_modifyTime;
		
		/// <summary>Gets or sets ModifyTime</summary>
        public DateTime? ModifyTime {
        	get { return m_modifyTime; }
        	set { m_modifyTime = value;}        
        }
		
	    #endregion
		
        #region ModifyUserID

        private Int64? m_modifyUserID;
		
		/// <summary>Gets or sets ModifyUserID</summary>
        public Int64? ModifyUserID {
        	get { return m_modifyUserID; }
        	set { m_modifyUserID = value;}        
        }
		
	    #endregion
		
        #region Status

        private Int32? m_status;
		
		/// <summary>Gets or sets Status</summary>
        public Int32? Status {
        	get { return m_status; }
        	set { m_status = value;}        
        }
		
	    #endregion

        /// <summary>
        /// 类型名称 1=栏目模板 2=新闻模板 3=列表页模板 4=专题模板 5=其他模板
        /// </summary>
        public string TypeName
        {
            get;
            set;
        }

        /// <summary>
        /// 状态名称 0=停用 1=启用 2=删除
        /// </summary>
        public string StatusName
        {
            get;
            set;
        }
	}
	
}
