//==============================================================================
//	CAUTION: This file is generated by IBatisNetGen.Entity.cst at 2011/9/14 21:40:03
//				Any manual editing will be lost in re-generation.
//==============================================================================
using System;
using System.Collections.Generic;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace CMS.Domain {
	
    /// <summary><c>UserInfo</c> Business Object.</summary>
    [Serializable]
    public partial class UserInfo {
        
        #region ID

        private Int64 m_iD;
		
		/// <summary>Gets or sets ID</summary>
        public Int64 ID {
        	get { return m_iD; }
        	set { m_iD = value;}        
        }
		
	    #endregion
		
        #region UserName

        private String m_userName;
		
		/// <summary>Gets or sets UserName</summary>
        [DisplayName("用户名")]
        [Required(ErrorMessage = "用户名不能为空")]
        [StringLength(32, ErrorMessage = "用户名不能超过32个字符")]
        public String UserName {
        	get { return m_userName; }
        	set { m_userName = value;}        
        }
		
	    #endregion
		
        #region Password

        private String m_password;
		
		/// <summary>Gets or sets Password</summary>
        [DisplayName("登录密码")]
        [Required(ErrorMessage = "登录密码不能为空")]
        [StringLength(33, ErrorMessage = "登录密码不能超过33个字符")]
        public String Password {
        	get { return m_password; }
        	set { m_password = value;}        
        }
		
	    #endregion

        #region RealName

        private String m_realName;

        /// <summary>Gets or sets RealName</summary>
        [DisplayName("真实姓名")]
        [Required(ErrorMessage = "真实姓名不能为空")]
        [StringLength(100, ErrorMessage = "真实姓名不能超过100个字符")]
        public String RealName
        {
            get { return m_realName; }
            set { m_realName = value; }
        }

        #endregion
		
        #region RoleID

        private Int64 m_roleID = 0;
		
		/// <summary>Gets or sets RoleID</summary>
        public Int64 RoleID {
        	get { return m_roleID; }
        	set { m_roleID = value;}        
        }
		
	    #endregion
		
        #region Department

        private String m_department = "";
		
		/// <summary>Gets or sets Department</summary>
        [DisplayName("所属部门")]
        [Required(ErrorMessage = "所属部门不能为空")]
        [StringLength(128, ErrorMessage = "所属部门不能超过128个字符")]
        public String Department {
        	get { return m_department; }
        	set { m_department = value;}        
        }
		
	    #endregion
		
        #region CreateTime

        private DateTime m_createTime;
		
		/// <summary>Gets or sets CreateTime</summary>
        public DateTime CreateTime {
        	get { return m_createTime; }
        	set { m_createTime = value;}        
        }
		
	    #endregion
		
        #region CreateUserID

        private Int64 m_createUserID = 0;
		
		/// <summary>Gets or sets CreateUserID</summary>
        public Int64 CreateUserID {
        	get { return m_createUserID; }
        	set { m_createUserID = value;}        
        }
		
	    #endregion
		
        #region Email

        private String m_email = "";
		
		/// <summary>Gets or sets Email</summary>
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email不能为空")]
        [RegularExpression(@"^\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$", ErrorMessage = "请输入正确的Email地址")]
        [StringLength(128, ErrorMessage = "Email不能超过128个字符")]
        public String Email {
        	get { return m_email; }
        	set { m_email = value;}        
        }
		
	    #endregion
		
        #region Status

        private Int32 m_status;
		
		/// <summary>Gets or sets Status</summary>
        public Int32 Status {
        	get { return m_status; }
        	set { m_status = value;}        
        }
		
	    #endregion

        /// <summary>
        /// 登录令牌
        /// </summary>
        public string Token
        {
            get;
            set;
        }
	}
	
}
